intex2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # the built-in Django administrator
    url(r'^admin/', admin.site.urls),

    # urls for any third-party apps go here

    # the DMP router - this should normally be the last URL listed
    url('', include('django_mako_plus.urls')),
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

 
# Create your models here.
class User(AbstractUser):
   def returnName(self):
       return self.first_name + ' ' + self.last_name; 

account/forms.py
from django import forms 
from django.contrib.auth.models import User
import django.contrib.auth
from django.contrib.auth import authenticate, login, logout 
from django.core.exceptions import ValidationError 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from account import models as amod

class loginForm(forms.Form):
    Username = forms.CharField()
    Password = forms.CharField(max_length=32, widget=forms.PasswordInput)

    def clean(self):
        #data = self.cleaned_data['Password']
        user = authenticate(username=self.cleaned_data['Username'], password=self.cleaned_data['Password'])
        if user is None:
            #ValueError("Username or password is incorrect")
            raise forms.ValidationError('Invalid Username or Password.')
        return self.cleaned_data

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = amod.User
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = amod.User
        fields = ('username', 'email')

account/views/index.py
from django.conf import settings
from django_mako_plus import view_function, jscontext
from datetime import datetime, timezone
from django import forms
from account.forms import loginForm
from account import models as amod
from django.contrib.auth import authenticate, login, logout 
from django.core.exceptions import ValidationError 
from django.shortcuts import render, redirect 
from django.http import HttpResponseRedirect


@view_function
def process_request(request):
    if request.method == 'POST':
        form = loginForm(request.POST)
        if form.is_valid():
          user = authenticate(username=request.POST['Username'], password=request.POST['Password'])
          login(request, user)
          request.session['pageMessage'] = "Welcome back " + user.username;
          request.session['showMessage'] = True
          return HttpResponseRedirect('/', user)
        else:
            forms.ValidationError("Wrongo")
    else:
        form = loginForm()

    context = {
        'form': form
    }

    return request.dmp.render('index.html', context)

account/views/logout.py
from django.conf import settings
from django_mako_plus import view_function, jscontext
from datetime import datetime, timezone
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render, redirect
from account.forms import loginForm
from account import models as amod
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError

@view_function
def process_request(request):
    context = {

    }
    logout(request)
    return redirect('/account/')

account/views/signup.py
from django.conf import settings
from django_mako_plus import view_function, jscontext
from datetime import datetime, timezone
from django import forms
from account.forms import loginForm
from account import models as amod
from django.contrib.auth import authenticate, login, logout 
from django.core.exceptions import ValidationError 
from django.shortcuts import render, redirect 
from django.http import HttpResponseRedirect
from account.forms import CustomUserCreationForm

@view_function
def process_request(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            request.session['pageMessage'] = "Thanks for signing up!";
            request.session['showMessage'] = True
            return HttpResponseRedirect('/', user)

    else:
        form = CustomUserCreationForm()

    context = {
        'form': form
    }

    return request.dmp.render('sign-up.html', context)

account/templates/index.html
<%inherit file="app_base.htm" />

<%block name="content">
    <div class="content">
        <!-- <div id="alignLeft">
            <div class="container text-center">
                <form method="POST" class="form-signin">
                    ${ csrf_input }
                    <img class="mb-4" src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg alt="" width="72" height="72">
                    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
                    <label for="id_Username" class="sr-only">User Name</label>
                    <input type="text" name="Username" required="" id="id_Username" class="form-control" placeholder="User Name" required="" autofocus="">
                    <label for="id_Password" class="sr-only">Password</label>
                    <input type="password" name="Password" maxlength="32" required="" id="id_Password" class="form-control" placeholder="Password" required="">
                    <br>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                    <p class="mt-5 mb-3 text-muted">© 2019</p>
                </form>
            </div>
        </div> -->
        <div class="container py-5">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="text-center text-white mb-4">Bootstrap 4 Login Form</h2>
                        <div class="row">
                            <div class="col-md-6 mx-auto">
            
                                <!-- form card login -->
                                <div class="card rounded-0">
                                    <div class="card-header">
                                        <h3 class="mb-0">Login</h3>
                                    </div>
                                    <div class="card-body">
                                        <form class="form" role="form" autocomplete="off" id="formLogin" novalidate="" method="POST">
                                            ${ csrf_input }
                                            <div class="form-group">
                                                    <label for="id_Username" class="sr-only">User Name</label>
                                                    <input type="text" name="Username" required="" id="id_Username" class="form-control" placeholder="User Name" required="" autofocus="">
                                                <div class="invalid-feedback">Oops, you missed this one.</div>
                                            </div>
                                            <div class="form-group">
                                                    <label for="id_Password" class="sr-only">Password</label>
                                                    <input type="password" name="Password" maxlength="32" required="" id="id_Password" class="form-control" placeholder="Password" required="">
                                                <div class="invalid-feedback">Enter your password too!</div>
                                            </div>
                                            <div>
                                                <label class="custom-control custom-checkbox">
                                                  <input type="checkbox" class="custom-control-input">
                                                  <span class="custom-control-indicator"></span>
                                                </label>
                                            </div>
                                            <button type="submit" class="btn btn-success btn-lg float-right" id="btnLogin">Login</button>
                                        </form>
                                    </div>
                                    <!--/card-block-->
                                </div>
                                <!-- /form card login -->
            
                            </div>
            
            
                        </div>
                        <!--/row-->
            
                    </div>
                    <!--/col-->
                </div>
                <!--/row-->
            </div>
            <!--/container-->
    </div>
</%block>

account/templates/sign-up.html
<%inherit file="app_base.htm" />

<%block name="content">
    <div class="content">
        <div class="container-fluid bg-light py-3">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card card-body">
                        <h3 class="text-center mb-4">Sign-up</h3>
                        <div class="alert alert-danger">
                            <a class="close font-weight-light" data-dismiss="alert" href="#">×</a>Password is too short.
                        </div>
                        <form method="POST">
                            ${ csrf_input }
                            <div class="form-group has-success">
                                <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" class="form-control input-lg" placeholder="User Name">
                            </div>
                            <div class="form-group has-success">
                                <input type="email" name="email" maxlength="254" id="id_email" class="form-control input-lg" placeholder="Email" />
                            </div>
                            <div class="form-group has-success">
                                <input type="password" name="password1" required="" id="id_password1" aria-autocomplete="list" class="form-control input-lg" placeholder="Password">
                            </div>
                            <div class="form-group has-success">
                                <input type="password" name="password2" required="" id="id_password2" class="form-control input-lg" placeholder="Confirm Password">
                            </div>
                            <div class="form-group">
                                <select class="form-control input-lg">
                                    <option selecterd="">Sequrity Question</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input class="form-control input-lg" placeholder="Sequrity Answer" name="answer" value="" type="text">
                            </div>
                            <div class="checkbox">
                                <label class="small">
                                    <input name="terms" type="checkbox">I have read and agree to the <a href="#">terms of service</a>
                                </label>
                            </div>
                            <input class="btn btn-lg btn-primary btn-block" value="Sign Me Up" type="submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</%block>